sudo: required
language: python
python:
  - '3.6'
env:
  global:
    - DOCKER_COMPOSE_VERSION: 1.26.0
services:
  - docker
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
install:
  - pip install -r requirements.txt
  - docker build -t odootest_runner .
  - docker-compose up -d
  - docker ps
script:
  - make tests
after_script:
  - docker-compose stop
after_success:
  - coveralls
notifications:
  email:
    recipients:
      - olivier.simon@youritfactory.com
    on_success: change
    on_failure: always
  slack:
    rooms:
      secure: ZniltJThkVEVKMPH4R0rPV8mz6vyycYcUCJa1gOVswAuiCYtHzAv7s42y726k0l/U+yZ+nnK5xYtWqs+BKjt6UGmekoTrVDqWYnVn/eUCiWj7GmKD1JPzFkR1cXDzbYpIbTte1pdRxmdTKUgFvgVRW65OaqvlK5BBP6RitfLJmuHBph6C8VQAjRfD2RlFpNosRJ2KkoeSfEDNbWlBX/RWL6AzouWUiU3BGhs9nGmI1IVzMR6gijusMDZmXLhFUZSfaN5NgRk01EGvGfz/GfOLxNVa+g9a1xACbNUqXvep2aJVVS5j+CaftOr7oRyZu2vbWuvGZIaXtYWyA2istFYDK/zJ0Fb3apLiuOb9HAqSOohvqyA28He/3gpvmgK+IDg6YOHULt6ywtGage3xMuQJgPGQjhc06mE06QeOatBR+B8+2ornf+YmlNKt2wd0FpkO2/Co3yeIANMsKybTHtg2z00g46KQKg8ye5pPr9TRMOJ922vu8/pEG0/fTBUI4N0cgjEwqUY1OQK89TD44IDorWHhNc4fLhHI4Hs6unqOsOLSGc7Ksuxr95kVMq2Eqv05Ves16xJDAPlnS2kZ/teEbjqf47fZBLKZGcHU9/Ogic3eXe87hroWNUToyJxQ2E9L4pnjJ2bmqht6cbAencqWB5p/dZGkY47D8N9pXwy4I0=
    on_success: always
    on_failure: always
